> min(survey$Height, na.rm = TRUE)
> max(survey$Height, na.rm = TRUE)
> mean(survey$Height, na.rm = TRUE)
> median(survey$Height, na.rm = TRUE)
> quantile(survey$Height, 0.25, na.rm = TRUE)
> quantile(survey$Height, 0.75, na.rm = TRUE)
> sd(survey$Height, na.rm = TRUE)
> var(survey$Height, na.rm = TRUE)
> diff(range(survey$Height, na.rm = TRUE))
> IQR(survey$Height, na.rm = TRUE)
> summary(survey$Height)
> fivenum(survey$Height)

> summary(survey$Height[survey$Sex == "Male"])
> sd(survey$Height[survey$Sex == "Male"], na.rm = TRUE)
> var(survey$Height[survey$Sex == "Male"], na.rm = TRUE)
> diff(range(survey$Height[survey$Sex == "Male"], na.rm = TRUE))
> IQR(survey$Height[survey$Sex == "Male"], na.rm = TRUE)
> fivenum(survey$Height[survey$Sex == "Male"])

> summary(survey$Height[survey$Sex == "Female"])
> sd(survey$Height[survey$Sex == "Female"], na.rm = TRUE)
> var(survey$Height[survey$Sex == "Female"], na.rm = TRUE)
> diff(range(survey$Height[survey$Sex == "Female"], na.rm = TRUE))
> IQR(survey$Height[survey$Sex == "Female"], na.rm = TRUE)
> fivenum(survey$Height[survey$Sex == "Female"])

> x.without.na <- survey$Height[!is.na(survey$Height)]
> x.mean <- mean(survey$Height, na.rm = TRUE)
> x.sd <- sd(survey$Height, na.rm = TRUE)
> sum(abs(x.without.na - x.mean) / x.sd < 1) / length(x.without.na)
